services:
  app-dev:
    build: .
    image: paxboard:dev
    command: ["python","-m","uvicorn","backend.app:app","--host","0.0.0.0","--port","8000","--reload"]
    ports: ["8000:8000"]
    environment:
      CSV_PATH: /data/flight_data.csv
      MU_PER_OFFICER: "0.50"
      ALPHA: "0.25"
      GREEN: "0.7"
      YELLOW: "0.9"
      TZ: Europe/Istanbul
    volumes:
      - ./backend:/app/backend
      - ./ui:/app/ui
      - ./data/flight_data.csv:/data/flight_data.csv:rw
    # platform: linux/amd64   # Apple Silicon + amd64 hedefi gerekiyorsa aç

  generator:
    image: paxboard:dev         # pandas hazır
    working_dir: /work
    volumes:
      - ./scripts:/work:ro
      - ./data/flight_data.csv:/data/flight_data.csv:rw
    command: ["python","/work/dummyGenerator.py","--out","/data/flight_data.csv"]
